In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Crime_Data_from_2020_to_2024.csv')

In [3]:
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,07/24/2024 12:00:00 AM,07/23/2024 12:00:00 AM,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,4000 W 23RD ST,NaN,34.0362,-118.3284
1004890,240104953,01/15/2024 12:00:00 AM,01/15/2024 12:00:00 AM,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,1300 W SUNSET BL,NaN,34.0685,-118.2460
1004891,240410786,10/14/2024 12:00:00 AM,10/11/2024 12:00:00 AM,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,1700 ALBION ST,NaN,34.0675,-118.2240
1004892,240309674,04/24/2024 12:00:00 AM,04/24/2024 12:00:00 AM,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,FLOWER ST,JEFFERSON BL,34.0215,-118.2868
1004893,240910892,08/13/2024 12:00:00 AM,08/12/2024 12:00:00 AM,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,6900 VESPER AV,NaN,34.1961,-118.4510

In [4]:
df.shape

(1004894, 28)

In [5]:
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,04/11/2021 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,10/21/2020 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,12/10/2024 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,12/24/2020 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,10/03/2020 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350

In [6]:
df.isnull().sum()

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151598
Vict Age                0
Vict Sex           144631
Vict Descent       144643
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677678
Weapon Desc        677678
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           935740
Crm Cd 3          1002580
Crm Cd 4          1004830
LOCATION                0
Cross Street       850666
LAT                     0
LON                     0
dtype: int64

In [7]:
df = df.drop(columns=['Mocodes'])

df = df.dropna(subset=['Crm Cd 1'])

df['Vict Sex'] = df['Vict Sex'].fillna('Unknown')
df['Vict Descent'] = df['Vict Descent'].fillna('Unknown')

df['Weapon Used Cd'] = df['Weapon Used Cd'].fillna(0)
df['Weapon Desc'] = df['Weapon Desc'].fillna('No Weapon')

df = df.drop(columns=['Premis Cd'])

df['Premis Desc'] = df['Premis Desc'].fillna('Unknown')

df = df.drop(columns=['Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4'])

df = df.drop(columns=['Cross Street'])

df['Vict Sex'] = df['Vict Sex'].replace({'X': 'Unknown'})

df.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
TIME OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Crm Cd Desc       0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Desc       0
Weapon Used Cd    0
Weapon Desc       0
Status            1
Status Desc       0
Crm Cd 1          0
LOCATION          0
LAT               0
LON               0
dtype: int64

-There are multiple columns with large amounts of null values. "Mocodes" describes how a crime was committed, such as if there was a weapon involved or if the victim is a family member. I believe this column is not necessary and should be dropped. It is messy and difficult to analyze, and we are more focused on what the crime is rather than how it was carried out. <br>-"Victim sex" and "descent" have a large amount of null values but they are necessary to understand the demographic information of this dataset. The values that are null will be filled with unknown to ensure they are accounted for. <br>-The column " Premis Desc" will be filled with "Unknown" to account for the missing values. "Premis Cd" is not necessary and will be dropped.<br>-There are two categories containing weapon info, "Weapon Used Cd" and "Weapon Desc." The null values will be filled with "No Weapon" to account for the crimes without weapons involved. <br>-The 4 columns named "Crm Cd" describe if a suspect has multiple charges. "Crm Cd 1" is the primary charge and any after that are secondary. There are 11 null values under "Crm Cd 1." These null values can be dropped from the dataset as they cannot be categorized. The remaining columns showing the other charges can all be dropped as well. The amount of null values is too high and they are not essential to understanding the dataset.<br>-Lastly, the column "Cross Street" is not essential to the dataset and will be dropped. The location and cordinates are already provided.

In [8]:
df['Status'].value_counts()

Status
IC    802761
AO    109799
AA     87152
JA      3285
JO      1879
CC         6
Name: count, dtype: int64

These are the LAPD case status codes. In order to understand the data it is essential to understand what each of these means.<br>
IC- Investigation Continuing (still active and open case)<br>
AO- Adult Other (adult was involved but not arrested)<br>
AA- Adult Arrest<br>
JA- Juvenile Other (juvenile was involved but not arrested)<br>
JO- Juvenile Arrest <br>
CC- Cleared by Other Means<br>

In [9]:
df['Date Rptd'] = pd.to_datetime(df['Date Rptd'])
df['DATE OCC'] = pd.to_datetime(df['DATE OCC'])

df['Year'] = df['DATE OCC'].dt.year
df['Month'] = df['DATE OCC'].dt.month
df['Month Name'] = df['DATE OCC'].dt.strftime('%B')
df['Day of Week'] = df['DATE OCC'].dt.strftime('%A')

df['Hour'] = df['TIME OCC'].astype(str).str.zfill(4).str[:2].astype(int)

C:\Users\logan\AppData\Local\Temp\ipykernel_23436\3877631484.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date Rptd'] = pd.to_datetime(df['Date Rptd'])
C:\Users\logan\AppData\Local\Temp\ipykernel_23436\3877631484.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DATE OCC'] = pd.to_datetime(df['DATE OCC'])

This code makes the data easier to understand and visualize. It reformats the dates when the crimes occured and were reported into a simpler format that reads YEAR-MONTH-DAY. It also creates five new columns "Year," "Month," "Month Name," "Day of the Week," and "Hour." These will make it easier to visualize and categorize the crimes.

In [10]:
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status Desc,Crm Cd 1,LOCATION,LAT,LON,Year,Month,Month Name,Day of Week,Hour
0,211507896,2021-04-11,2020-11-07,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,Invest Cont,354.0,7800 BEEMAN AV,34.2124,-118.4092,2020,11,November,Saturday,8
1,201516622,2020-10-21,2020-10-18,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,Invest Cont,230.0,ATOLL AV,34.1993,-118.4203,2020,10,October,Sunday,18
2,240913563,2024-12-10,2020-10-30,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,Invest Cont,354.0,14600 SYLVAN ST,34.1847,-118.4509,2020,10,October,Friday,12
3,210704711,2020-12-24,2020-12-24,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,Invest Cont,331.0,6000 COMEY AV,34.0339,-118.3747,2020,12,December,Thursday,13
4,201418201,2020-10-03,2020-09-29,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,Invest Cont,420.0,4700 LA VILLA MARINA,33.9813,-118.4350,2020,9,September,Tuesday,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004889,240710284,2024-07-24,2024-07-23,1400,7,Wilshire,788,1,510,VEHICLE - STOLEN,...,Invest Cont,510.0,4000 W 23RD ST,34.0362,-118.3284,2024,7,July,Tuesday,14
1004890,240104953,2024-01-15,2024-01-15,100,1,Central,101,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,Invest Cont,745.0,1300 W SUNSET BL,34.0685,-118.2460,2024,1,January,Monday,1
1004891,240410786,2024-10-14,2024-10-11,2330,4,Hollenbeck,421,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,Invest Cont,341.0,1700 ALBION ST,34.0675,-118.2240,2024,10,October,Friday,23
1004892,240309674,2024-04-24,2024-04-24,1500,3,Southwest,358,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,Invest Cont,230.0,FLOWER ST,34.0215,-118.2868,2024,4,April,Wednesday,15
1004893,240910892,2024-08-13,2024-08-12,2300,9,Van Nuys,914,1,510,VEHICLE - STOLEN,...,Invest Cont,510.0,6900 VESPER AV,34.1961,-118.4510,2024,8,August,Monday,23

In [11]:
descent_map = {
    'A': 'Other Asian',
    'B': 'Black',
    'C': 'Chinese',
    'D': 'Cambodian',
    'F': 'Filipino',
    'G': 'Guamanian',
    'H': 'Hispanic/Latin/Mexican',
    'I': 'American Indian/Alaskan Native',
    'J': 'Japanese',
    'K': 'Korean',
    'L': 'Laotian',
    'O': 'Other',
    'P': 'Pacific Islander',
    'S': 'Samoan',
    'U': 'Hawaiian',
    'V': 'Vietnamese',
    'W': 'White',
    'X': 'Unknown',
    'Z': 'Asian Indian'
}

df['Vict Descent'] = df['Vict Descent'].map(descent_map)

In [12]:
df['Vict Descent'] = df['Vict Descent'].fillna('Unknown')

I think it is much easier to categorize the data when the Victim's demographic data is spelled out instead of being a single letter.

In [13]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name',
       'rpt_dist_no', 'part_1-2', 'crm_cd', 'crm_cd_desc', 'vict_age',
       'vict_sex', 'vict_descent', 'premis_desc', 'weapon_used_cd',
       'weapon_desc', 'status', 'status_desc', 'crm_cd_1', 'location', 'lat',
       'lon', 'year', 'month', 'month_name', 'day_of_week', 'hour'],
      dtype='object')

This was done simply to make the columns easier to work with in SQL.

In [14]:
df.isnull().sum()

dr_no             0
date_rptd         0
date_occ          0
time_occ          0
area              0
area_name         0
rpt_dist_no       0
part_1-2          0
crm_cd            0
crm_cd_desc       0
vict_age          0
vict_sex          0
vict_descent      0
premis_desc       0
weapon_used_cd    0
weapon_desc       0
status            1
status_desc       0
crm_cd_1          0
location          0
lat               0
lon               0
year              0
month             0
month_name        0
day_of_week       0
hour              0
dtype: int64

In [15]:
df = df.dropna(subset=['status'])

In [16]:
df.isnull().sum()

dr_no             0
date_rptd         0
date_occ          0
time_occ          0
area              0
area_name         0
rpt_dist_no       0
part_1-2          0
crm_cd            0
crm_cd_desc       0
vict_age          0
vict_sex          0
vict_descent      0
premis_desc       0
weapon_used_cd    0
weapon_desc       0
status            0
status_desc       0
crm_cd_1          0
location          0
lat               0
lon               0
year              0
month             0
month_name        0
day_of_week       0
hour              0
dtype: int64

In [17]:
df.loc[:, 'vict_sex'] = df['vict_sex'].replace({'H': 'Unknown', '-': 'Unknown'})

"H" and "-" were recoded to "Unknown" as H is an alternate code LAPD uses for unspecified sex.

In [18]:
df.to_csv('crime_data_cleaned.csv', index=False)